version: '3.8'

services:
  python:
    build: ./app/
    ports:
    - 8000:5000
    volumes:
    - ./:/app

  mysqldb:
    image: mysql:8
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=p@ssword
    - MYSQL_USER=root
    - MYSQL_PASSWORD=p@ssword
    - MYSQL_DATABASE=DB
    volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
